scopes:
  - paths: ['/home/volhovm/org/study.org', '/home/volhovm/org/work.org', '/home/volhovm/org/private.org']
  - name: test
    paths: ['/home/volhovm/code/orgstat/test.org']
timelineDefault:
  legend: false
  colWidth: 1.2
  colHeight: 1.1
reports:
  # For timeline
  - name: thisWeekTop
    range: week
    modifiers:
      - type: prune
        path: /study/
        depth: 1
      - type: prune
        path: /work/
        depth: 1

  # Statistics
  - name: thisWeekA1
    range: week
    modifiers:
      - type: filterbytag
        tag: A1
  - name: thisWeekA2
    range: week
    modifiers:
      - type: filterbytag
        tag: A2
  - name: thisWeekA3
    range: week
    modifiers:
      - type: filterbytag
        tag: A3
  - name: thisWeekI
    range: week
    modifiers:
      - type: filterbytag
        tag: I
  - name: thisWeekWork
    range: week
    modifiers:
      - type: filterbytag
        tag: work
  - name: thisWeekStudy
    range: week
    modifiers:
      - type: filterbytag
        tag: study
  - name: thisWeekE
    range: week
    modifiers:
      - type: filterbytag
        tag: E
  - name: testReport
    range: month
    scope: test
outputs:
  - name: thisWeekTimeline
    report: thisWeekTop
    type: timeline
  - name: thisWeekStats
    type: summary
    template: "%thisWeekWork%<fc=#429942>/</fc>%thisWeekStudy% %thisWeekA1%<fc=#429942>/</fc>%thisWeekA2%<fc=#429942>/</fc>%thisWeekA3% %thisWeekI%<fc=#429942>/</fc>%thisWeekE%"
  - name: thisWeekStatsBlock
    type: block
    unicode: true
    maxLength: 60
    report: testReport

outputDir: /home/volhovm/code/orgstat/
todoKeywords: [ TODO, STARTED, WAITING, DONE, CANCELED, TD, ST, WT, CL, DN ]
colorSalt: 3
