scopes:
  - paths: ['/home/volhovm/org/study.org', '/home/volhovm/org/work.org', '/home/volhovm/org/private.org.gpg']
timelineDefault:
  colWidth: 1.2
  colHeight: 1.1
reports:
#  # Current week
#  - name: curWeekFull
#    type: 
#      type: timeline
#      range: week
#      topDay: 4
#  - name: curWeekTop
#    type: 
#      type: timeline
#      range: week
#      topDay: 4
#    modifiers:
#      - type: prune
#        path: /study/
#        depth: 1
#      - type: prune
#        path: /work/
#        depth: 1
#  - name: curWeekStudy
#    type: 
#      type: timeline
#      range: week
#      topDay: 3
#    modifiers: 
#      - type: select 
#        path: study
#      - type: prune
#        path: /
#        depth: 2
#  - name: curWeekWork
#    type: 
#      type: timeline
#      range: week
#      topDay: 3
#    modifiers: 
#      - type: select 
#        path: work/Serokell
#      - type: prune
#        path: /
#        depth: 2
#  - name: curWeekPrivate
#    type: 
#      type: timeline
#      range: week
#      topDay: 5
#    modifiers: 
#      - type: select 
#        path: private/Living the life
   # Previous week
   - name: prevWeekFull
     type: 
       type: timeline
       range: week-1
   - name: prevWeekTop
     type: 
       type: timeline
       range: week-1
     modifiers:
       - type: prune
         path: /study/
         depth: 1
       - type: prune
         path: /work/
         depth: 1
   - name: prevWeekStudy
     type: 
       type: timeline
       range: week-1
     modifiers: 
       - type: select 
         path: study/
       - type: prune
         path: /
         depth: 3
   - name: prevWeekWork
     type: 
       type: timeline
       range: week-1
     modifiers: 
       - type: select 
         path: work/Serokell
       - type: prune
         path: /
         depth: 2
   - name: prevWeekPrivate
     type: 
       type: timeline
       range: week-1
     modifiers: 
       - type: select 
         path: private/
output: /home/volhovm/reps/orgstat/
todoKeywords: [ TODO, STARTED, WAITING, DONE, CANCELED ]
colorSalt: 3
