scopes:
  - paths: ['/home/volhovm/org/study.org', '/home/volhovm/org/work.org', '/home/volhovm/org/private.org']
  - name: test
    paths: ['/home/volhovm/code/orgstat/test.org']
timelineDefault:
  legend: false
  colWidth: 1.2
  colHeight: 1.1
  background: "#ffffff"
reports:
  - name: thisWeekProductive
    range: week
    modifiers:
      - type: filterbytag
        tags: [study,work,H]

  # Statistics
  - name: thisWeekStudy
    range: week
    modifiers:
      - type: filterbytag
        tag: study
  - name: thisWeekWork
    range: week
    modifiers:
      - type: filterbytag
        tag: work
  - name: thisWeekA
    range: week
    modifiers:
      - type: filterbytag
        tag: A
  - name: thisWeekH
    range: week
    modifiers:
      - type: filterbytag
        tag: H
  - name: thisWeekE
    range: week
    modifiers:
      - type: filterbytag
        tag: E
  - name: thisWeekI
    range: week
    modifiers:
      - type: filterbytag
        tag: I
  - name: testReport
    range: month
    scope: test
outputs:
  - name: thisWeekTimeline
    report: thisWeekProductive
    type: timeline
  - name: thisWeekStats
    type: summary
    template: "w%thisWeekWork%<fc=#429942>/</fc>s%thisWeekStudy%<fc=#429942>/</fc>h%thisWeekH% i%thisWeekI% a%thisWeekA%<fc=#429942>/</fc>e%thisWeekE%"
  - name: thisWeekStatsBlock
    type: block
    unicode: true
    maxLength: 60
    report: testReport

outputDir: /home/volhovm/code/orgstat/
todoKeywords: [ TODO, STARTED, WAITING, DONE, CANCELED, TD, ST, WT, CL, DN ]
colorSalt: 3
