scopes:
  - paths: ['/home/volhovm/org/study.org', '/home/volhovm/org/work.org', '/home/volhovm/org/private.org']
timelineDefault:
  colorSalt: 3
  legend: false
  colWidth: 1.2
  colHeight: 1.1
reports:
  - name: thisWeekProductive
    range: week
    modifiers:
      - type: filterbytag
        tags: [s,w,H]

  # Statistics
  - name: thisWeekStudy
    range: week
    modifiers:
      - type: filterbytag
        tag: s
  - name: thisWeekWork
    range: week
    modifiers:
      - type: filterbytag
        tag: w
  - name: thisWeekA
    range: week
    modifiers:
      - type: filterbytag
        tag: A
  - name: thisWeekH
    range: week
    modifiers:
      - type: filterbytag
        tag: H
  - name: thisWeekE
    range: week
    modifiers:
      - type: filterbytag
        tag: E
  - name: thisWeekI
    range: week
    modifiers:
      - type: filterbytag
        tag: I
outputs:
  - name: thisWeekTimeline
    report: thisWeekProductive
    type: timeline
  - name: thisWeekStats
    type: summary
    template: "s%thisWeekStudy% h%thisWeekH% e%thisWeekE% <fc=#355254>a%thisWeekA%</fc>"
  - name: thisWeekStatsScript
    type: script
    scriptPath: ~/dotfiles/scripts/orgstat_format_bar.sh
    reports: [thisWeekStudy,thisWeekH,thisWeekA,thisWeekE]
  - name: thisWeekStatsBlock
    type: block
    report: testReport

outputDir: /home/volhovm/code/orgstat/
todoKeywords: [ TODO, STARTED, WAITING, DONE, CANCELED, TD, ST, WT, CL, DN ]
