scopes:
  - paths: ['/home/volhovm/org/study.org', '/home/volhovm/org/private.org']
timelineDefault:
  colorSalt: 3
  legend: false
  colWidth: 1.2
  colHeight: 1.1
reports:
  - name: thisWeekAll
    range: week
  - name: thisWeekProductive
    range: week
    modifiers:
      - type: filterbytag
        tags: [M,H]

  # Statistics
  - name: thisWeekM
    range: week
    modifiers:
      - type: filterbytag
        tag: M
  - name: thisWeekA
    range: week
    modifiers:
      - type: filterbytag
        tag: A
  - name: thisWeekH
    range: week
    modifiers:
      - type: filterbytag
        tag: H
  - name: thisWeekE
    range: week
    modifiers:
      - type: filterbytag
        tag: E

  - name: todayM
    range: day
    modifiers:
      - type: filterbytag
        tag: M
  - name: todayA
    range: day
    modifiers:
      - type: filterbytag
        tag: A
  - name: todayH
    range: day
    modifiers:
      - type: filterbytag
        tag: H
  - name: todayE
    range: day
    modifiers:
      - type: filterbytag
        tag: E


outputs:
  - name: thisWeekTimeline
    report: thisWeekProductive
    type: timeline
  - name: thisWeekStats
    type: summary
    template: "s%thisWeekM% h%thisWeekH% e%thisWeekE% <fc=#355254>a%thisWeekA%</fc>"
  - name: thisWeekStatsScript
    type: script
    interpreter: "/bin/env sh"
    scriptPath: ~/dotfiles/scripts/orgstat_format_bar.sh
    reports: [thisWeekM,thisWeekH,thisWeekA,thisWeekE,todayM,todayH,todayA,todayE]

  # For debug
  - name: thisWeekStatsBlock
    type: block
    report: thisWeekProductive

outputDir: /home/volhovm/code/orgstat/
todoKeywords: [ TD, ST, WT, CL, DN ]
